### ISSUE TITLE
Figure out skateboard! (MVP for initial release(MVP)

### ISSUE THREAD

**Issue by DanLombardy** [haverchuck/oligarch_fantasty_league#3]
FIgure out what the most viable product is for our initial release. Comparison on contributors?

**Comment by jhnmllr** [comment]
So, we are all kind of doing this one I'm sure...

'Give user political information' is probably as simple of a goal as possible. I think one thing that complicates even an MVP is, *how much* information and *what* information do we give the user and how do we make this decision? I've been doing some catch up so if you guys have already concretely figured this out hopefully I'll get up to speed today.

My thought is, just to get started we could make sure that our app can fetch from each database, process the result and display it to the user. So, if our app has the capability to do campaign finance look ups, voting record, etc we should maybe focus on getting the app to serve some info on some arbitrary politician in each database to get started. Then, later, worry about how to serve specific information determined by user input etc.
